# Generated by Django 5.0.6 on 2024-06-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_userbookrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bad'), (2, 'Not good'), (3, 'Good'), (4, 'Great'), (5, 'Perfect')]),
        ),
    ]
