# Generated by Django 5.0.6 on 2024-06-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_book_readers_alter_book_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bad'), (2, 'Not good'), (3, 'Good'), (4, 'Great'), (5, 'Perfect')], null=True),
        ),
    ]
