# Generated by Django 5.0.6 on 2024-06-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_userbookrelation_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookrelation',
            name='comment',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
