# Generated by Django 5.0.6 on 2024-06-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_userbookrelation_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
